# Name: Mahmoud Yousif, Student Number: 22703519
# Declaration: I acknowledge the DCU Academic Integrity Policy.

myshell: src/myshell.c src/utility.c src/myshell.h
	gcc -Wall src/myshell.c src/utility.c -o bin/myshell